name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@42cdb151b217e714c6e85a41ef3d2adddf8321d3
        with:
          disable-package-manager-cache: true
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@42cdb151b217e714c6e85a41ef3d2adddf8321d3
      - name: Setup Bazel Remote Caching
        uses: angular/dev-infra/github-actions/bazel/configure-remote@42cdb151b217e714c6e85a41ef3d2adddf8321d3
        with:
          google_credential: ${{ secrets.RBE_TRUSTED_BUILDS_USER }}
      # TODO: switch this over to `bazel test` once bazel tests exist
      - run: pnpm bazel build  //...
